### ISSUE TITLE
Ordering Boards

### ISSUE THREAD

**Issue by ModestMC** [turgu1/ESP32-Sensing-Device#1]
Hey Guy,

I was just looking at some old WROOMs I have left over from my senior design project and thinking I should finally fix the PCB and order a new one. Instead, I decided to try finally playing with the Inkplate I got for Christmas. I decided to look at your repos and was both surprised and very happy to find this one!

I'm making this issue because ordinarily, you wind up having to order PCBs in sets of three or five. However, in my experience you're unlikely to use them all, especially when prototyping things(JLPCB winds up charging more for the shipping than the board). If you're interested, I'd be happy to buy one of the PCBs from you.

Cheers,
Mitchell

**Comment by turgu1** [comment]
Hello Mitchell,
I'm waiting to get the boards. They have been prepared by PCBWay last week and I expect to get them in a week or two (transport through DHL from China). Where are you located?

**Comment by ModestMC** [comment]
Nebraska! Should be the same continent I believe. Also, what are you hoping to do with the board once you have them?

For the sake of simplicity, if you'd prefer feel welcome to send an email to [redacted]

**Comment by turgu1** [comment]
I'm afraid I cannot send one to you. I have 10 of these boards that are coming. Two will be used for prototyping, the others will be installed in my house for sensing (water leak, smokes detectors, mailbox, mesh net). If I had one to spare with you, I would have to charge at least 20$ to send it to you (One hour of my time to prepare and go to the Post Office, complete a customs form, the cost of the car ride to go there, the cost of the PCB).

When you consider the price paid for 10 boards, It's about 3$ per board (etching cost: 5$, transportation: $23). This is not that expansive. Even if you need only one PCB, it's still a bargain. Here in Quebec City, a local etching company requests at least 100$ to produce a single board.

Digikey offers a service in California that wouldn't cost more than ordering from China I believe (at least for US people) for such a small PCB (31mm x 28 mm) when you add the cost of production and transportation (they call their low price etching DK RED). But you would not get the same quality of service from a shop like PCBWay (they do a lot of verification on the PCBs before shipping).

**Comment by turgu1** [comment]
Here is the price at Digikey for 10 boards:
![image](https://user-images.githubusercontent.com/174329/160613065-acd197df-b634-4a06-9b0e-65b9853f13e5.png)

**Comment by ModestMC** [comment]
No worries, I completely understand. I assumed this was a prototype board, but I should have realized someone as experienced as you probably knows exactly what the board they're looking for should do.

In that case, I will probably just fork your board, make some minor tweaks (mostly access to a few more pins) then put in an order myself. I already have to order stuff for the university so it should be simple enough to tack mine onto their shipping.

Thanks for getting back to me! Is there a good way I can drop you a line if I have questions about design elements of the board?

**Comment by turgu1** [comment]
You are welcome. As I will mount and test the first PCB, I will add some info on my discoveries in the documentation. So stay tuned

Also, you may look at the potential issues I raised in the documentation...

Cheers!!
Guy
